import type { Metadata } from "next";
import SessionWrapper from './components/SessionWrapper';
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "Nextjs 14 Login",
    template: "%s | Login"
  },
  description: 'Generated by NextJS14',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body>{children}</body>
      </html>
    </SessionWrapper>
  );
}
